#!/usr/bin/env python3

import re
import sys
import glob
import os.path
import adlib
try:
    import xlsxwriter
except ImportError:
    print("ERROR: Please install xlswriter to run this script\n")
    print("  $ sudo apt install python3-xlsxwriter\n")
    sys.exit(1)

#
# Global settings

OUT_FILE = 'configurations.xlsx'

ESR_PREVIOUS = 'esr60'
ESR_CURRENT = 'esr68'

WORKBOOK_DEF = [
    ('基本設定', [
        'Install',
        'Application',
        'Admin',
        'Security',
        'Privacy',
        'Startup',
        'Websearch',
        'Location',
        'Download',
        'Tab',
        'Network',
        'Update',
        'Ui',
        'Script',
        'Plugin',
        'External',
        'Stability',
        'Appearance',
        'Performance',
        'Addon-IEView',
        'Addon-FireIE',
    ]),
    ('機能無効化', [
        'MenuShortcut',
    ]),
]

DEFAULT_FORMAT = {
    'valign': 'top',
    'border': 1,
    'font_size': 8,
    'font_name': 'MS Gothic',
    'text_wrap': 1
}

def load_as_dict(path):
    try:
        data = adlib.load(path)
    except IOError:
        return {}

    res = {}
    for item in data:
        for opt in item['opts']:
            res[opt['opt_id']] = opt['conf']
    return res

def check_conf(conf, opt_id):
    if opt_id not in conf:
        return ('', '')
    return ('y', conf[opt_id])

def setup_conditional_format(sheet, formats):
    countif = 'COUNTIFS($A$2:$A$9999,"",$B$2:$B$9999,$B2)<>COUNTIF($B$2:$B$9999,$B2)'

    # THE ORDER OF RULES BELOW IS IMPORTANT. THE EARLIER RULE TAKES
    # PRECEDENCE OVER THE LATER. SO PLEASE TAKE CARE WHEN EDITTING THEM.

    # DEPRECATED
    sheet.conditional_format('B2:C9999', {
        'type':     'formula',
        'criteria': 'ISNUMBER(FIND("廃止",$C2))',
        'format':   formats['deprecated']
    })

    sheet.conditional_format('D2:I9999', {
        'type':     'formula',
        'criteria': 'ISNUMBER(FIND("廃止",$E2))',
        'format':   formats['deprecated']
    })

    # QUESTION
    sheet.conditional_format('D2:I9999', {
        'type':     'formula',
        'criteria': '$A2 = "?"',
        'format':   formats['question']
    })

    # SELECTED (NEW)
    sheet.conditional_format('D2:I9999', {
        'type':     'formula',
        'criteria': 'AND($H2 = "", $A2 <> "")',
        'format':   formats['new']
    })

    sheet.conditional_format('B2:C9999', {
        'type':     'formula',
        'criteria': 'AND($H2 = "", %s)'  % countif,
        'format':   formats['new']
    })

    # SELECTED
    sheet.conditional_format('D2:I9999', {
        'type':     'formula',
        'criteria': '$A2 <> ""',
        'format':   formats['selected']
    })

    sheet.conditional_format('B2:C9999', {
        'type':     'formula',
        'criteria': countif,
        'format':   formats['selected']
    })


def main(args):
    wb = xlsxwriter.Workbook(OUT_FILE)

    conf_new = {}
    conf_old = {}

    for arg in args:
        if ESR_CURRENT in arg:
            conf_new = load_as_dict(arg)
        if ESR_PREVIOUS in arg:
            conf_old = load_as_dict(arg)

    formats = {
        'default':    wb.add_format(DEFAULT_FORMAT),
        'deprecated': wb.add_format({'bg_color': '#CCCCCC', 'border': 1}),
        'selected':   wb.add_format({'bg_color': '#ffd700', 'border': 1}),
        'question':   wb.add_format({'bg_color': '#90ee90', 'border': 1}),
        'new':        wb.add_format({'bg_color': '#ff8c00', 'border': 1}),
    }

    for title, files in WORKBOOK_DEF:
        sheet = wb.add_worksheet(title)
        setup_conditional_format(sheet, formats)

        sheet.write(0, 0, '選択')
        sheet.write(0, 1, '項目番号')
        sheet.write(0, 2, '項目名')
        sheet.write(0, 3, '選択番号')
        sheet.write(0, 4, '選択肢')
        sheet.write(0, 5, '標準設定 (%s)' % ESR_CURRENT)
        sheet.write(0, 6, '導入設定 (%s)' % ESR_CURRENT)
        sheet.write(0, 7, '標準設定 (%s)' % ESR_PREVIOUS)
        sheet.write(0, 8, '導入設定 (%s)' % ESR_PREVIOUS)

        sheet.set_column(0, 8, None, formats['default'])
        sheet.set_column(0, 0, 3)
        sheet.set_column(1, 1, 12)
        sheet.set_column(2, 2, 30)
        sheet.set_column(3, 3, 5)
        sheet.set_column(4, 4, 20)
        sheet.set_column(5, 5, 40)
        sheet.set_column(6, 6, 40)
        sheet.set_column(7, 7, 40)
        sheet.set_column(8, 8, 40)

        row = 1
        for fn in files:
            curr = adlib.load(os.path.join(ESR_CURRENT, fn))
            prev = load_as_dict(os.path.join(ESR_PREVIOUS, fn))

            for data in curr:
                if len(data['opts']) > 1:
                    sheet.merge_range(row, 1, row + len(data['opts']) - 1, 1, '')
                    sheet.merge_range(row, 2, row + len(data['opts']) - 1, 2, '')

                for d in data['opts']:
                    mark, conf = check_conf(conf_new, d['opt_id'])

                    sheet.write(row, 0, mark, formats['default'])
                    sheet.write(row, 1, data['item_id'])
                    sheet.write(row, 2, data['item_title'])
                    sheet.write(row, 3, d['opt_no'])
                    sheet.write(row, 4, d['opt_title'])
                    sheet.write(row, 5, d['conf'].strip())
                    sheet.write(row, 6, conf, formats['default'])
                    sheet.write(row, 7, prev.get(d['opt_id'], ""), formats['default'])
                    sheet.write(row, 8, conf_old.get(d['opt_id'], ""), formats['default'])
                    row += 1

    wb.close()
    print('Generated:', OUT_FILE)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
