#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# build-xlsx - Generate a spread sheet from files
#
# USAGE
#
# (1) Output an empty sheet
#
#     $ build-xlsx -o config.xlsx
#
# (2) Generate a filled sheet
#
#     $ build-xlsx esr78.txt esr91.txt ... verify-targets-to-chapters.csv
#     $ build-xlsx -p esr78.txt -c esr91.txt
#     $ build-xlsx -d ESR78:esr78.txt -d ESR91:esr91.txt -d "ESR91 variation:esr91-variation.txt"
#
# DEFINITION OF TERMS IN THIS MODULE
#
#     For example, about "Security-9-3 about:configの利用の可否：禁止する" on Firefox ESR91:
#
#     * category: "Security"
#     * item:     "Security-9"
#     * option:   "Security-9-1", "Security-9-2", "Security-9-3", and others
#     * config:
#       * curr/prev: curr=ESR91, prev=ESR78 (versions)
#       * config:    `"BlockAboutConfig": true,` or others, defined in the given esr91.txt
#       * template:  `"BlockAboutConfig": true,` or others, defined in the file esr91/Security

import re
import sys
import glob
import getopt
import csv
import os

BASEDIR = os.path.dirname(os.path.realpath(__file__))
sys.path.append(BASEDIR)

import adlib
try:
    import xlsxwriter
except ImportError:
    print('ERROR: Please install xlswriter to run this script\n')
    print('  $ sudo apt install python3-xlsxwriter\n')
    sys.exit(1)

#
# Global settings

ESR_PREVIOUS = 'esr78'
ESR_CURRENT  = 'esr91'
CHAPTERS_CSV = 'verify-targets-to-chapters.csv'

WORKBOOKS = [
    ('基本設定', [
        'Install',
        'Application',
        'Admin',
        'Security',
        'Privacy',
        'Startup',
        'Websearch',
        'Location',
        'Download',
        'Tab',
        'Network',
        'Update',
        'Ui',
        'Script',
        'Plugin',
        'External',
        'Stability',
        'Appearance',
        'Performance',
        'Addon-IEView',
        'Addon-FireIE',
        'Addon-Acrobat',
        'Addon-Skysea',
    ]),
    ('機能無効化', [
        'MenuShortcut',
    ]),
]

DEFAULT_FORMAT = {
    'valign':    'top',
    'border':    1,
    'font_size': 8,
    'font_name': 'MS Gothic',
    'text_wrap': 1
}

BASE_COLUMNS = [ # label, width
    ('カテゴリー',              10), # A
    ('項目設定番号',            10), # B
    ('カスタマイズ項目 (目的)', 30), # C
    ('選択肢番号',              5),  # D
    ('選択肢',                  20), # E
    ('設定内容の雛形\n(%s)' % ESR_CURRENT.upper(), 40), # F
]

def variation_columns(key, prev_key):
    return [ # label, width
        ('反映した設定値\n(%s)' % key,       40),
        ('%s→%sでの変更' % (prev_key, key), 10),
    ]

VERIFICATION_COLUMNS = [ # label, width
    ('検証手順書対応番号', 10),
    ('',                   12),
]

PREV_VERSION_COLUNBS = [ # label, width
    ('設定内容の雛形\n(%s)' % ESR_PREVIOUS.upper(), 40),
    ('反映した設定値\n(%s)' % ESR_PREVIOUS.upper(), 40),
]

#
# XLSX writer

class ConfigurationSheet:

    def __init__(self, all_configs, verification_chapters, formats, sheet):
        self._all_configs           = all_configs
        self._verification_chapters = verification_chapters
        self._formats               = formats
        self._sheet                 = sheet

    def write(self, row, column, contents, format):
        self._sheet.write(row, column, contents, self._formats[format])

    def _set_column(self, row, column, width, format = None):
        if format:
            self._sheet.set_column(row, column, width, self._formats[format])
        else:
            self._sheet.set_column(row, column, width)

    def write_header(self):
        sheet  = self._sheet
        format = 'center'

        sheet.freeze_panes(1, 0)
        sheet.set_row(0, 25)

        self._write_header_columns(BASE_COLUMNS, format, 0)
        column_offset = len(BASE_COLUMNS)

        last_variation = ESR_PREVIOUS.upper()
        for variation in self._all_configs.keys():
            if variation == ESR_PREVIOUS.upper():
                continue
            columns = variation_columns(variation, last_variation)
            self._write_header_columns(columns, format, column_offset)
            column_offset += len(columns)
            last_variation = variation

        self._write_header_columns(VERIFICATION_COLUMNS, format, column_offset)
        column_offset += len(VERIFICATION_COLUMNS)

        self._write_header_columns(PREV_VERSION_COLUNBS, format, column_offset)
        column_offset += len(PREV_VERSION_COLUNBS)

        self._set_column(0, column_offset - 1, None, 'default')

    def _write_header_columns(self, columns, format, column_offset):
        sheet = self._sheet
        for index, column in enumerate(columns):
            label, width = column
            self.write(0, column_offset + index, label, format)
            self._set_column(column_offset + index, column_offset + index, width)

    def merge_category_heading(self, row, items):
        self._sheet.merge_range(row, 0, row + self._count_options(items) - 1, 0, '')

    def _count_options(self, config):
        return sum(len(item['options']) for item in config)

    def try_merge_item_heading(self, row, item):
        if len(item['options']) > 1:
            sheet = self._sheet
            sheet.merge_range(row, 1, row + len(item['options']) - 1, 1, '')
            sheet.merge_range(row, 2, row + len(item['options']) - 1, 2, '')

    def write_legend(self, row):
        self.write(row,     1, '',                                     'selected')
        self.write(row,     2, '前バージョンから引き続き利用する項目', 'noborder')
        self.write(row + 1, 1, '',                                     'selected_changed')
        self.write(row + 1, 2, '前バージョンから異同がある項目',       'noborder')
        self.write(row + 2, 1, '',                                     'deprecated')
        self.write(row + 2, 2, '廃止済みの項目',                       'noborder')

    def iterate_all_config_items(self):
        return self._all_configs.items()

    def get_verification_chapter(self, option_id, key):
        self._verification_chapters.get(option_id, '省略')

class ConfigurationRow:

    def __init__(self, sheet, index, item, option, category,
                 prev_configs, prev_config,
                 template_curr_config, template_prev_config):
        self._sheet                = sheet
        self._index                = index
        self._item                 = item
        self._option               = option
        self._category             = category
        self._prev_configs         = prev_configs
        self._prev_config          = prev_config
        self._template_curr_config = template_curr_config
        self._template_prev_config = template_prev_config

    def write(self):
        # This must be done for all rows, otherwise merged cells will have
        # a partial border line just for the first row.
        self._write_item_heading_columns()

        column_offset, format, verification_chapter = self._write_item_variations_columns()

        self._write_item_leading_columns(format)
        self._write_item_trailing_columns(format, column_offset, verification_chapter)

    def _write_column(self, column, contents, format):
        self._sheet.write(self._index, column, contents, format)

    def _sanitize_config(self, config):
        return re.sub(' *[^:]+:\n', '', config).strip()

    def _write_item_heading_columns(self):
        item = self._item
        self._write_column(0, self._category, 'default') # A

        format = 'default'
        if self._is_deprecated(item['title']):
            format = 'deprecated'

        self._write_column(1, int(item['index']), format) # B
        self._write_column(2, item['title'],      format) # C

    def _write_item_leading_columns(self, format):
        option = self._option
        self._write_column(3, int(option['option_index']), format) # D
        self._write_column(4, option['option_title'],      format) # E
        self._write_column(5, self._template_curr_config,  format) # F

    def _write_item_variations_columns(self):
        sheet     = self._sheet
        item      = self._item
        option    = self._option
        option_id = option['option_id']

        column_offset        = len(BASE_COLUMNS)
        format               = 'default'
        verification_chapter = ''

        last_configs        = self._prev_configs
        last_applied_config = self._prev_config
        for key, variation_config in sheet.iterate_all_config_items():
            if key == key == ESR_PREVIOUS.upper():
                continue

            status           = ''
            variation_format = 'default'
            applied_variation_config = variation_config.get(option_id, {'config':''})['config']

            if self._is_deprecated(item['title']) or self._is_deprecated(option['option_title']):
                variation_format = 'deprecated'
            elif option_id in variation_config:
                verification_chapter = sheet.get_verification_chapter(option_id, '省略')
                if option_id not in last_configs:
                    variation_format, status = 'selected_changed', '新規'
                elif self._sanitize_config(last_applied_config) != self._sanitize_config(applied_variation_config):
                    variation_format, status = 'selected_changed', '変更あり'
                else:
                    variation_format, status = 'selected', ''
            elif last_configs == self._prev_configs:
                if self._sanitize_config(self._template_curr_config) != self._sanitize_config(self._template_prev_config):
                  verification_chapter = sheet.get_verification_chapter(option_id, '省略')
                  if self._template_prev_config == '':
                      variation_format, status = 'changed', '新規（未設定）'
                  else:
                      variation_format, status = 'changed', '変更あり（未設定）'
            else:
                if self._sanitize_config(last_applied_config) != self._sanitize_config(applied_variation_config):
                    status = '削除'

            if last_configs == self._prev_configs:
              format = variation_format

            self._write_column(column_offset,     applied_variation_config, variation_format)
            self._write_column(column_offset + 1, status,                   variation_format)
            column_offset += 2
            last_configs        = variation_config
            last_applied_config = applied_variation_config

        return [column_offset, format, verification_chapter]

    def _is_deprecated(self, value):
        return '廃止' in value

    def _write_item_trailing_columns(self, format, column_offset, verification_chapter):
        self._write_column(column_offset,     verification_chapter,       'default')
        self._write_column(column_offset + 1, '',                         'noborder')
        self._write_column(column_offset + 2, self._template_prev_config, format)
        self._write_column(column_offset + 3, self._prev_config,          format)

def generate_xlsx(workbook, all_configs, verification_chapters, exclude_worksheets):
    formats = create_formats(workbook)
    prev_configs = all_configs[ESR_PREVIOUS.upper()]

    for title, sources in WORKBOOKS:
        if title in exclude_worksheets:
            continue

        sheet = ConfigurationSheet(
            all_configs,
            verification_chapters,
            formats,
            workbook.add_worksheet(title),
        )
        sheet.write_header()

        row_index = 1
        for source in sources:
            # We always output config items based on sources for the current version.
            # In other words, the "current version" needs to define all deprecated/obsolete items
            # if they still need to be visible in the output sheet.
            base_items = adlib.load(os.path.join(BASEDIR, ESR_CURRENT, source))
            prev_items = adlib.load_as_dict(os.path.join(BASEDIR, ESR_PREVIOUS, source))

            sheet.merge_category_heading(row_index, base_items)

            for item in base_items:
                sheet.try_merge_item_heading(row_index, item)

                for option in item['options']:
                    option_id = option['option_id']
                    row = ConfigurationRow(
                        sheet,
                        row_index,
                        item,
                        option,
                        source,
                        prev_configs,
                        prev_config = prev_configs.get(option_id, {'config':''})['config'],
                        template_curr_config = option['config'].strip(),
                        template_prev_config = prev_items.get(option_id, {'config':''})['config'],
                    )
                    row.write()
                    row_index += 1

        sheet.write_legend(row_index + 1)

def create_formats(workbook):
    def new_format(**kwargs):
        return workbook.add_format(dict(DEFAULT_FORMAT, **kwargs))
    return {
        'default':          new_format(),
        'noborder':         new_format(border = 0),
        'center':           new_format(align = 'center'),
        'changed':          new_format(bold = True),
        'deprecated':       new_format(bg_color = '#dddddd'),
        'question':         new_format(bg_color = '#90ee90'),
        'selected':         new_format(bg_color = '#fffa95'),
        'selected_changed': new_format(bg_color = '#ffb571'),
    }

#
# main

def load_verification_chapters(path):
    try:
        with open(path) as file:
            return dict(csv.reader(file))
    except FileNotFoundError:
        return {}

def main(args):
    all_configs = {}
    outfile     = 'config.xlsx'
    exclude_worksheets = []

    opts, args = getopt.getopt(args, 'o:x:p:c:d:')
    for key, value in opts:
        if key == '-o':
            outfile = value
        elif key == '-x':
            exclude_worksheets = value.split(',')
        elif key == '-p':
            all_configs[ESR_PREVIOUS.upper()] = value
        elif key == '-c':
            all_configs[ESR_CURRENT.upper()] = value
        elif key == '-d':
            parts = value.split(':', 1)
            all_configs[parts[0]] = parts[1]

    verification_chapters = {}
    for arg in args:
        if ESR_PREVIOUS in arg and not ESR_PREVIOUS.upper() in all_configs:
            print('%s -> %s' % (ESR_PREVIOUS, arg))
            all_configs[ESR_PREVIOUS.upper()] = arg
        elif ESR_CURRENT in arg and not ESR_CURRENT.upper() in all_configs:
            print('%s -> %s' % (ESR_CURRENT, arg))
            all_configs[ESR_CURRENT.upper()] = arg
        elif CHAPTERS_CSV in arg:
            print('Loading', os.path.basename(arg))
            verification_chapters = load_verification_chapters(arg)

    for label, path in all_configs.items():
        all_configs[label] = adlib.load_as_dict(path)

    with xlsxwriter.Workbook(outfile) as workbook:
        generate_xlsx(workbook, all_configs, verification_chapters, exclude_worksheets)

    print('Generated:', workbook.filename)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
