#!/usr/bin/env python3
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# cat-verify - Generate a Markdown verification manual
#
# USAGE
#
#     $ cat-verify -c config.txt -a variable.txt

import re
import sys
import glob
import getopt
import logging
import textwrap
import csv
import os
import collections

BASEDIR = os.path.dirname(os.path.realpath(__file__))
sys.path.append(BASEDIR)

import adlib

try:
    import jinja2
except ImportError:
    print("ERROR: Please install jinja2 to run this script\n")
    print("  $ sudo apt install python3-jinja2\n")
    sys.exit(1)

#
# GLOBALS

TEMPLATE = """
## {opt_id}

『{item_title}』
{opt_title_sub_out}

**検証手順**

{conf}
"""

TEMPLATE_PRETEXT = """
## {opt_title}

{conf}
"""

TEMPLATE_OPTIONS = """
# オプション画面を使用した検証

## 事前準備

- 前項に引き続き検証するか、または以下の状態を整えておく。
    - 作成済みの `{{meta_installer_file_name}}*.exe` を検証用ユーザーとして実行し、カスタマイズ済みFirefoxのインストールを完了している。
      管理者権限を要求された場合は、`管理者`ユーザーで認証する。
- Firefoxを起動する。
- パネルメニューからオプションを開く。
"""

TEMPLATE_ABOUT_CONFIG = """
# about:configを使用した検証

## 事前準備

- 前項に引き続き検証するか、または以下の状態を整えておく。
    - 作成済みの `{{meta_installer_file_name}}*.exe` を検証用ユーザーとして実行し、カスタマイズ済みFirefoxのインストールを完了している。
      管理者権限を要求された場合は、`管理者`ユーザーで認証する。
- ポリシー設定から一時的に `DisableDeveloperTools` を削除しておく。
- ポリシー設定から一時的に `BlockAboutConfig` を削除しておく。
- Firefoxを起動する。
- `about:config`を開く。
"""

TEMPLATE_ABOUT_POLICIES = """
# about:policiesを使用した検証

## 事前準備

- 前項に引き続き検証するか、または以下の状態を整えておく。
    - 作成済みの `{{meta_installer_file_name}}*.exe` を検証用ユーザーとして実行し、カスタマイズ済みFirefoxのインストールを完了している。
      管理者権限を要求された場合は、`管理者`ユーザーで認証する。
- Firefoxを起動する。
- `about:policies`を開く。
- 「有効」を選択する。
"""

FILES = [
    'PRETEXT',
    'Install',
    'Application',
    'Admin',
    'Security',
    'Privacy',
    'Startup',
    'Websearch',
    'Location',
    'Download',
    'Tab',
    'Network',
    'Update',
    'Ui',
    'Script',
    'Plugin',
    'External',
    'Stability',
    'Appearance',
    'Performance',
    'Addon-IEView',
    'Addon-FireIE',
    'Addon-Acrobat',
]

SPECIALS = [
    'OVERWRITE',
    'OPTIONS',
    'ABOUT_CONFIG',
    'ABOUT_POLICIES',
]

#
# Utils

def parse_special(text):
    ht = text.split('\n', maxsplit=1)

    if ht[0] in SPECIALS:
        return (ht[0], ht[1])

    return ('', text)

def apply_vars(items, vars):
    for item in items:
        for opt in item['opts']:
            if opt['opt_id'] not in vars:
                continue

            sp, text = parse_special(vars[opt['opt_id']])
            if sp == 'OVERWRITE':
                opt['conf'] = text
            else:
                opt['conf'] += text
    return items

PAT_PRETEXT_OPTION = re.compile('.+-0-%d+\Z')

def create_template(manual, conf, vars):
    items_options = []
    items_about_config = []
    items_about_policies = []

    all_ids = []

    template = vars.get('COVER', '') + '\n'
    template += "# 事前準備"

    for item in manual['PRETEXT']:
        for opt in item['opts']:
            template += TEMPLATE_PRETEXT.format(**opt) + '\n'

    for items in manual.values():
        tmp = ''

        for item in items[1:]:
            for opt in item['opts']:
                if opt['opt_id'] not in conf:
                    continue

                sp, text = parse_special(opt['conf'])
                if sp == 'OPTIONS':
                    items_options.append((opt['opt_id'], opt['opt_title_sub'], text))
                    all_ids.append((opt['opt_id'], opt['opt_title_sub'], 'specials-options'))
                    continue
                elif sp == 'ABOUT_CONFIG':
                    items_about_config.append((opt['opt_id'], opt['opt_title_sub'], text))
                    all_ids.append((opt['opt_id'], opt['opt_title_sub'], 'specials-about-config'))
                    continue
                elif sp == 'ABOUT_POLICIES':
                    items_about_policies.append((opt['opt_id'], opt['opt_title_sub'], text))
                    all_ids.append((opt['opt_id'], opt['opt_title_sub'], 'specials-about-policies'))
                    continue

                opt['opt_title_sub_out'] = opt['opt_title_sub']
                if opt['opt_title_sub_out'] != '':
                    opt['opt_title_sub_out'] = '（' + opt['opt_title_sub_out'] + '）'

                tmp += TEMPLATE.format(**opt, **item) + '\n'
                if not re.match(PAT_PRETEXT_OPTION, opt['opt_id']):
                    all_ids.append((opt['opt_id'], opt['opt_title_sub'], opt['opt_id']))

        if not tmp:
            continue  # Nothing to verify

        template += '\n# %s' % items[0]['item_title']
        for opt in items[0]['opts']:
            template += TEMPLATE_PRETEXT.format(**opt) + '\n'
        template += tmp

    if items_options:
        template += TEMPLATE_OPTIONS
        for opt_id, opt_title_sub, text in items_options:
            template += '\n## %s %s\n' % (opt_id, opt_title_sub)
            template += text + '\n'

    if items_about_config:
        template += TEMPLATE_ABOUT_CONFIG
        for opt_id, opt_title_sub, text in items_about_config:
            template += '\n## %s %s\n' % (opt_id, opt_title_sub)
            template += text + '\n'

    if items_about_policies:
        template += TEMPLATE_ABOUT_POLICIES
        for opt_id, opt_title_sub, text in items_about_policies:
            template += '\n## %s %s\n' % (opt_id, opt_title_sub)
            template += text + '\n'

    template += '\n' + vars.get('POSTSCRIPT', '')


    if all_ids:
        #all_ids.sort(key=lambda x: [x[0].split('-')[0]] + list(map(int, x[0].split('-')[1:])))
        #template += '\n# 索引\n'
        template += '\n# 検証対象項目一覧\n'
        for opt_id, opt_title_sub, reference in all_ids:
            template += '\n* %s %s' % (opt_id, opt_title_sub)

    return template

#
# Main

def usage(err):
    print('error: %s' % err, file=sys.stderr)
    print('usage: %s INFILE' % sys.argv[0], file=sys.stderr)
    sys.exit(1)

def main(args):
    conf = {}
    vars = {}

    opts, args = getopt.getopt(args, 'c:a:')
    for k, v in opts:
        if k == '-c':
            conf = adlib.load_as_dict(v)
        elif k == '-a':
            vars = adlib.load_variables(v)

    manual = collections.OrderedDict()
    for fn in FILES:
        items = adlib.load('verify/%s' % fn)
        manual[fn] = apply_vars(items, vars)

    template = create_template(manual, conf, vars)

    logging.basicConfig(format="\033[31m%(message)s\033[0m")
    log = logging.getLogger(__name__)

    env = jinja2.Environment(undefined=jinja2.make_logging_undefined(log))
    print(env.from_string(template).render(vars))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
