#!/usr/bin/env ruby
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# cat-manual - Render verification manual templates
#
# USAGE
#
# (1) Output a verification manual
#
#    $ cat-manual --config=config-esr68.txt --json=verification.json manual.md
#
# (2) Output a list of chapters (for build-xlsx)
#
#    $ cat-manual --config=config-esr68.txt --json=verification.json --output-chapters manual.md

require "csv"
require "json"
require "optparse"

begin
  require "mustache"
rescue
  STDERR.puts("ERROR: Please install mustache to run this script\n\n")
  STDERR.puts("  $ sudo apt install ruby-mustache\n\n")
  abort()
end

# This is a set of snippets that are used to fill placeholders in the
# template. You can override any of them through the '--json' option.
VARIABLES = {
  cover:                         nil,
  is_upgrade_from_uncontrolled:   true,
  firefox_version:                "68.0 ESR",
  windows_version:                "Windows 7",
  configuration_sheet_name:       "config.xlsx",
  meta_installer_name:            "Fx Meta Installer",
  meta_installer_file_name:       "FxMetaInstaller",
  meta_installer_version:         "60.0",
  install_path:                   "C:\\Program Files (x86)\\Mozilla Firefox",
  install_path_32bit:             "C:\\Program Files\\Mozilla Firefox", # インストール先を固定しておらず、32bit環境と64bit環境でインストール先が変わる場合
  desktop_shortcut_path:          "C:\\Users\\Public\\Desktop\\Firefox.lnk",
  start_menu_shortcut_path:       "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Firefox.lnk",
  finish_title:                   "Mozilla Firefox",
  finish_message:                 "インストールが完了しました",
  restart_title:                  "Mozilla Firefox",
  restart_message:                "今すぐコンピュータを再起動しますか？",
  mcd_local_file:                 "autoconfig.cfg",
  special_profile_path:           "%AppData%\\Mozilla\\Firefox\\Profiles",
  #special_profile_actual_path:    "`C:\\Users\\(ユーザー名)\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles`",
  special_profile_name:           "Special",
  use_separate_profile:           false,
  start_with_no_remote:           false,
  home_page:                      "http://?????",
  window_title:                   "Mozilla Firefox",
  exe_name:                       "firefox",
  disabled_about_pages:           "about:robots",
  history_expiration_max_pages:   "???",
  expire_history_by_days_version: "Flexible Expire History by Days",
  max_cache_size_in_megabytes:    "???",
  download_dir:                   "C:\\?????",
  proxy_host:                     "10.0.2.2",
  proxy_auth_user:                "clearcode",
  pac_url:                        "http://??????/proxy.pac",
  pac_url_setup:                  "",
  ntlm_single_signon_hosts:       "????,????,????",
  max_connections:                       "6",
  max_persistent_connections_per_server: "2",
  max_persistent_connections_per_proxy:  "2",
  max_pipelining_requests:               "32",
  user_agent_name:                "Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/60.0",
  jar_file_sample_url_base:       "http://www.clear-code.com/temp",
  imported_certs:                 "検証用証明書（example.com）, (発行者名1)/(証明署名1), (発行者名1)/(証明署名2), ...",
  use_disableaboutconfig:         true,
  use_disableupdate:              true,
  use_disableaddons:              true,
  use_globalchromecss:            true,
  use_uitextoverrider:            true,
  use_silverlight:                true,
  use_policyengine:               true,
  java_download_url:              "https://java.com/ja/download/",
  flash_download_url:             "https://get.adobe.com/jp/flashplayer/",
  acrobat__download_url:          "https://get.adobe.com/jp/reader/",
  shockwave__download_url:        "https://get.adobe.com/jp/shockwave/",
  silverlight_download_url:       "http://www.microsoft.com/silverlight/resources/install.aspx",
  wmp__download_url:              "http://www.interoperabilitybridges.com/Windows-Media-Player-Firefox-Plugin-Download",
}

class TemplateResolver
  class << self
    def resolve(contents, variables)
      new(contents, variables).resolve
    end
  end

  attr_reader :verify_targets

  def initialize(contents, variables)
    @contents = contents
    @variables = variables
    @verify_targets = []
  end

  def resolve(config)
    prepare_firefox_version_variables
    prepare_customizations_variables(config) if config
    @variables["TRUE"] = true
    @variables["FALSE"] = false
    resolve_and_conditions
    resolve_or_conditions
    @variables["disable_devtools"] = %w/
      MenuShortcut-10
      MenuShortcut-11
      MenuShortcut-12
      MenuShortcut-13
      MenuShortcut-14
      MenuShortcut-15
      MenuShortcut-16
      MenuShortcut-17
      MenuShortcut-18
      MenuShortcut-20
      MenuShortcut-21
      MenuShortcut-22
      MenuShortcut-23
      MenuShortcut-24
      MenuShortcut-25
      MenuShortcut-26
      MenuShortcut-28
      MenuShortcut-29
      MenuShortcut-57
      MenuShortcut-64
      MenuShortcut-65
      Security-9-3
    /.any? do |key|
      @variables.include?(key)
    end
    Mustache.render(@contents, @variables)
  end

  private
  def prepare_firefox_version_variables
    current_firefox_major_version = @variables[:firefox_version].split(".").first.to_i
    @variables["firefox#{current_firefox_major_version}"] = true
    (24..99).each do |version|
      @variables["firefox#{version}_or_older"] = current_firefox_major_version <= version
      @variables["firefox#{version}_or_later"] = current_firefox_major_version >= version
    end
  end

  def prepare_customizations_variables(config)
    config.keys.each do |key|
      @verify_targets << key
      @variables[key] = true
      if key.count("-") > 1
        chosen_sub_index = key.split("-").last.to_i
        base_key = key.gsub(/-[^-]+\z/, "")
        @variables[base_key] = true
        (1..10).each do |sub_index|
          unless sub_index == chosen_sub_index
            @variables["#{base_key}-#{sub_index}"] = false
          end
        end
      end
    end
  end

  AND_CONDITIONS_MATCHER = /\{\{([#^\/])([^&}]+\&\&[^}]+)\}\}/
  def resolve_and_conditions
    @contents.gsub!(AND_CONDITIONS_MATCHER) do |match|
      prefix = match.gsub(AND_CONDITIONS_MATCHER, "\\1")
      variable_names = match.gsub(AND_CONDITIONS_MATCHER, "\\2").split("&&").collect do |name|
        name.strip
      end
      if variable_names.all?{|name| @variables[name] }
        "{{#{prefix}TRUE}}"
      else
        "{{#{prefix}FALSE}}"
      end
    end
  end

  OR_CONDITIONS_MATCHER = /\{\{([#^\/])([^|}]+\|\|[^}]+)\}\}/
  def resolve_or_conditions
    @contents.gsub!(OR_CONDITIONS_MATCHER) do |match|
      prefix = match.gsub(OR_CONDITIONS_MATCHER, "\\1")
      variable_names = match.gsub(OR_CONDITIONS_MATCHER, "\\2").split("||").collect do |name|
        name.strip
      end
      variable_names.select! do |name|
        @variables[name]
      end
      if variable_names.empty?
        "{{#{prefix}FALSE}}"
      else
        "{{#{prefix}#{variable_names.sort.first}}}"
      end
    end
  end
end

class ContentsCleaner
  class << self
    def cleanup(contents)
      new(contents).cleanup
    end
  end

  def initialize(contents)
    introduction, contents = contents.split(/<!-- *VERIFICATIONS ARE FROM HERE *-->/)
    @introduction = introduction
    @contents = contents

    # Allow overriding the cover page via JSON
    @introduction = VARIABLES[:cover] if VARIABLES[:cover]
    if @introduction.is_a?(Array)
        @introduction = @introduction.join("\n")
    end
  end

  def cleanup
    cleanup_separators
    cleanup_no_child_parents
    cleanup_no_verification_steps
    cleanup_no_verification_sections
    cleanup_blank_chapters
    cleanup_blank_subsections

    @contents.gsub!(/^[ \t]*<!--[^>]*-->\n|<!--[^>]*-->/, "")

    cleanup_blank_lines

    "#{@introduction}\n#{@contents}"
  end

  private

  SEPARATORS_MATCHER = /<!-- *[-=]+ *-->/
  def cleanup_separators
    @contents.gsub!(SEPARATORS_MATCHER, "")
  end

  BLANK_LINE_MATCHER = /^( *([-*]|[0-9]+\. ).+\n)\n+( *([-*]|[0-9]+\. ))/m
  def cleanup_blank_lines
    while @contents.match(BLANK_LINE_MATCHER) do
      @contents.sub!(BLANK_LINE_MATCHER, "\\1\\3")
    end
  end

  NO_CHILD_PARENTS_MATCHER = /^[0-9]+\. 以下の(アドオン|カスタマイズ)を[有無]効化する。(\n+(^[0-9#]|\z))/m
  def cleanup_no_child_parents
    while @contents.match(NO_CHILD_PARENTS_MATCHER) do
      @contents.sub!(NO_CHILD_PARENTS_MATCHER, "\\2")
    end
  end

  NO_VERIFICATION_STEP_GROUPS_MATCHER = /^<!-- *GROUP *-->[^<]*\n *- *確認項目\n+<!-- *\/ *GROUP *-->/
  NO_VERIFICATION_STEPS_MATCHER = /^ *- *確認項目\n+( ?[0-9]\. |^#)/m
  def cleanup_no_verification_steps
    while @contents.match(NO_VERIFICATION_STEP_GROUPS_MATCHER) do
      @contents.sub!(NO_VERIFICATION_STEP_GROUPS_MATCHER, "")
    end

    while @contents.match(NO_VERIFICATION_STEPS_MATCHER) do
      @contents.sub!(NO_VERIFICATION_STEPS_MATCHER, "\\1")
    end
  end

  NO_VERIFICATION_SECTIONS_MATCHER = /^## [^#]+^### 確認する項目$\s*^###.*?(^##? |\z)/m
  def cleanup_no_verification_sections
    while @contents.match(NO_VERIFICATION_SECTIONS_MATCHER) do
      @contents.sub!(NO_VERIFICATION_SECTIONS_MATCHER, "\\1")
    end
  end

  BLANK_CHAPTERS_MATCHER = /^# [^#]+(^# |\z)/m
  def cleanup_blank_chapters
    while @contents.match(BLANK_CHAPTERS_MATCHER) do
      @contents.sub!(BLANK_CHAPTERS_MATCHER, "\\1")
    end
  end

  BLANK_SUBSECTIONS_MATCHER = /^### (準備|後始末)(\n+(^#|\z))/m
  def cleanup_blank_subsections
    while @contents.match(BLANK_SUBSECTIONS_MATCHER) do
      @contents.sub!(BLANK_SUBSECTIONS_MATCHER, "\\2")
    end
  end
end

def output_verify_targets_to_sections_list(path, contents, verify_targets)
  items_to_sections = {}
  contents.split(/^#[^#]/).each_with_index do |chapter, chapter_number|
    next if chapter_number <= 1
    chapter.split(/^##[^#]/).each_with_index do |section, section_number|
      next if section_number.zero?
      section_id = "#{chapter_number}.#{section_number}"
      items = section.match(/^### *確認する項目\s*([^#]+)\n#/)
      if items.nil?
        STDERR.puts  "Error: no verification target in: #{section}"
        next
      end
      items = items[1]
      items.each_line do |item|
        item.gsub!(/\A\s*-\s*|\s*\n?\z/, "")
        item.sub!(/(-[^-]+)-[^-]+\z/, "\\1")
        next if item.empty?
        items_to_sections[item] ||= []
        items_to_sections[item] << section_id
      end
    end
  end

  CSV($stdout) do |rows|
    verify_targets.each do |target|
      section_ids = items_to_sections[target.sub(/(-[^-]+)-[^-]+\z/, "\\1")]
      if section_ids
        rows << [target, section_ids.join("\n")]
      else
        STDERR.puts "  Warning: no verification for #{target}\n"
      end
    end
  end
end

def main()
  po = ARGV.getopts('', 'template:', 'config:', 'json:', 'output-chapters')
  basedir = File.dirname($0)
  manfile = "#{basedir}/manual.md"

  if ARGV.length > 0
    manfile = ARGV[0]
  end

  contents = File.read(manfile)

  if po['json']
    VARIABLES.merge!(JSON.parse(open(po['json']).read(), :symbolize_names => true))
  end

  if po['config']
    config = JSON.parse(`#{basedir}/format-config #{po['config']}`)
  end

  if VARIABLES["install_path_32bit"] == VARIABLES["install_path"]
    VARIABLES.delete("install_path_32bit")
  end

  resolver = TemplateResolver.new(contents, VARIABLES)
  contents = resolver.resolve(config)
  contents = ContentsCleaner.cleanup(contents)

  if po['output-chapters']
      STDERR.puts "Generating #{po['chapter']}..."
      output_verify_targets_to_sections_list(po['chapter'], contents, resolver.verify_targets)
  else
      puts(contents)
  end
end

if __FILE__ == $0
    main()
end
