#!/usr/bin/env python3
#
# txt2mcd - Generate MCD config file from text
#
# Copyright (C) Clear Code, Inc. 2019
#
# USAGE
#
#   $ txt2mcd config-esr60.txt


import re
import sys
import glob
import os

BASEDIR = os.path.dirname(os.path.realpath(__file__))
sys.path.append(BASEDIR)

import adlib

def usage():
    print('Usage: %s config-esr60.txt' % sys.argv[0])

#
# Global settings

ORDER = [
    'Install',
    'Application',
    'Admin',
    'Security',
    'Privacy',
    'Startup',
    'Websearch',
    'Location',
    'Download',
    'Tab',
    'Network',
    'Update',
    'Ui',
    'Script',
    'Plugin',
    'External',
    'Stability',
    'Appearance',
    'Performance',
    'Addon-IEView',
    'Addon-FireIE',
    'MenuShortcut',
]

def dosort(key):
    tag, tid, oid = key.split('-')
    tid = re.sub('[^0-9]', '', tid)
    oid = re.sub('[^0-9]', '', oid)
    return (ORDER.index(tag), int(tid), int(oid))

def main(args):
    if len(args) < 1:
        usage()
        sys.exit(1)

    dic = adlib.load_as_dict(args[0])
    keys  = list(dic.keys())
    keys.sort(key=dosort)

    for key in keys:
        if dic[key].strip() == '-':
            continue
        print('//', key)
        print(dic[key])
        print()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
