// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"simple-tab-groups_drive4ik-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"simple-tab-groups_drive4ik-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200817153328");
user_pref("extensions.lastAppVersion", "78.2.0");
user_pref("extensions.lastPlatformVersion", "78.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b1e39572-736b-446a-94b8-a0bc572e694e\",\"formautofill@mozilla.org\":\"6ec06027-66ed-4634-92ad-ca6aea23d613\",\"screenshots@mozilla.org\":\"641adb1d-e714-45a1-abbf-cea2260e7be2\",\"webcompat-reporter@mozilla.org\":\"5b81a19b-a2d2-42ca-a29c-863eeee2c05b\",\"webcompat@mozilla.org\":\"5d2dca3d-a649-47d3-92f7-4e09d780a6a9\",\"default-theme@mozilla.org\":\"298aa175-7266-4af2-b57e-b0a87cc6a420\",\"google@search.mozilla.org\":\"01798b10-84ea-484a-913a-a1aaea1c3dce\",\"wikipedia@search.mozilla.org\":\"7a007a96-2e98-4e83-80a8-095089f3c80c\",\"yahoo-jp-auctions@search.mozilla.org\":\"f8c4abc2-d681-4596-8829-d4e93e6187aa\",\"bing@search.mozilla.org\":\"f6696a75-3b3f-4039-90a0-50d44dd336cb\",\"rakuten@search.mozilla.org\":\"bac09490-12c4-4cef-9575-ce8c46a2f37a\",\"yahoo-jp@search.mozilla.org\":\"223d86e2-3f4c-4ba0-a5d9-e5686826752d\",\"amazon@search.mozilla.org\":\"41b0159b-2eb8-41ea-b154-891d930bde84\",\"ddg@search.mozilla.org\":\"08f3b908-0884-47f5-a4fc-d96fea405063\",\"oshiete-goo@search.mozilla.org\":\"d41d83ae-5ab0-4046-a9d1-ddad6202964c\",\"simple-tab-groups@drive4ik\":\"953b4f63-2f0e-4b37-9508-4003bbfdc246\"}");
