require "rake/clean"
require "tempfile"

#MD_FILES = FileList["*.md"]
MD_FILES = FileList["verification_manual.md"]
PDF_FILES = MD_FILES.map{|file| file.ext(".pdf") }
VARIABLES = {
  firefox_version:                "52.0 ESR",
  windows_version:                "Windows 7",
  configuration_sheet_name:       "customization-items.ods",
  meta_installer_name:            "Fx Meta Installer",
  meta_installer_file_name:       "FxMetaInstaller",
  meta_installer_version:         "52.0",
  install_path:                   "C:\\\\Program Files (x86)\\\\Mozilla Firefox",
  desktop_shortcut_path:          "C:\\\\Users\\\\Public\\\\Desktop\\\\Mozilla Firefox.lnk",
  start_menu_shortcut_path:       "C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\Mozilla Firefox.lnk",
  finish_title:                   "Mozilla Firefox",
  finish_message:                 "インストールが完了しました",
  restart_title:                  "Mozilla Firefox",
  restart_message:                "今すぐコンピュータを再起動しますか？",
  mcd_local_file:                 "autoconfig.cfg",
  special_profile_path:           "%AppData%\\\\Mozilla\\\\Firefox\\\\Profiles",
  special_profile_name:           "Special",
  home_page:                      "http://?????",
  window_title:                   "Mozilla Firefox",
  disabled_about_pages:           "about:robots",
  history_expiration_max_pages:   "???",
  expire_history_by_days_version: "Flexible Expire History by Days",
  max_cache_size_in_megabytes:    "???",
  download_dir:                   "C:\\\\?????",
  proxy_host:                     "10.0.2.2",
  proxy_auth_user:                "clearcode",
  pac_url:                        "http://??????/proxy.pac",
  pac_url_setup:                  "",
  ntlm_single_signon_hosts:       "????,????,????",
  user_agent_name:                "Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0",
  jar_file_sample_url_base:       "http://www.clear-code.com/temp",
  imported_certs:                 "(発行者名1)/(証明署名1), (発行者名1)/(証明署名2), ...",
  java_download_url:              "https://java.com/ja/download/",
  flash_download_url:             "https://get.adobe.com/jp/flashplayer/",
  acrobat__download_url:          "https://get.adobe.com/jp/reader/",
  shockwave__download_url:        "https://get.adobe.com/jp/shockwave/",
  silverlight_download_url:       "http://www.microsoft.com/silverlight/resources/install.aspx",
  wmp__download_url:              "http://www.interoperabilitybridges.com/Windows-Media-Player-Firefox-Plugin-Download",
}

CLOBBER.include(PDF_FILES)

task :default => :pdf

desc "Generate PDF"
task :pdf => PDF_FILES

rule ".pdf" => [".md", "Rakefile"] do |t|
  require "mustache"
  Tempfile.open("firefox-verification_manual") do |file|
    contents = File.read(t.source)
    contents = contents.gsub(/^[ \t]*<!--[^>]*-->\n|<!--[^>]*-->/, "")
    file.puts(Mustache.render(contents, VARIABLES))
    file.flush
    sh "pandoc", "-f", "markdown+ignore_line_breaks", "-o", t.name,
       "--table-of-contents", "--toc-depth=3",
       "-N",
       "-V", "documentclass=ltjsarticle",
       "-V", "classoption=titlepage",
       "--latex-engine=lualatex", file.path
  end
end
